  
name: Automated Build

on:
  push:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build Library (MSVC16)
      run: |
        cd
        msbuild.exe Development.sln /property:Configuration=Release
        cd ../..
      shell: cmd
