name: Continuous Integration

on:
  push:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild Set Up
      uses: microsoft/setup-msbuild@v1

    - name: Build Game
      run: |
        cd
        msbuild.exe Development.sln /p:Configuration=Release
        cd ../..
      shell: cmd
