
name: Continuous Delivery

on:

  push:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
     - uses: actions/checkout@master
     - name: Archive Release
       uses: thedoctor0/zip-release@master
       with:
        filename: 'Full_Studios-The_Hunter_Odyssey_v0.8.zip'
        exclusions: '*.gitignore* /*Development.sln /*CONVENTIONS /*Screenshots /*Game /*docs /*Build /*.github'

     - name: Upload Release
       uses: ncipollo/release-action@v1.8.3
       with:
        tag: ${{ startsWith(github.ref, 'refs/tags/') }}
        artifacts: "Full_Studios-The_Hunter_Odyssey_v0.8.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
